### ISSUE TITLE
Chart not compatible with K8S >=1.16

### ISSUE THREAD

**Issue by ClementGautier** [SubstraFoundation/substra-backend#256]
Hello there,

One of the daemonset deployed when you use the feature flag "gpu" (daemonset-nvidia-plugin.yaml) is using the wrong api version and it result in this error: `no matches for kind "DaemonSet" in version "extensions/v1beta1"` I suggest removing the feature and pointing to the Nvidia device plugin documentation: https://github.com/NVIDIA/k8s-device-plugin

**Comment by Kelvin-M** [comment]
Hello !
Yes, `DaemonSet`  is now an `apiVersion: 'app/v1'` instead of `extensions/v1beta1` (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)
We can see that nvidia has updated its kubernetes manifest on `master` branch : https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta6/nvidia-device-plugin.yml
We have several choices :
- Update the `DaemonSet`'s `apiversion` to match the new nvidia manifest and tell user that substra with gpu need the use of kubernetes version >= 1.16
- Do as you said, remove the nvidia part and let the user install the nvidia `DaemonSet`

I'm more in favor of the second solution as it depends on kubernetes version and presence of nvidia hardware on the cluster.
